logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
logging.level.org.springframework.web: TRACE
logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE

server:
  port: '3031'
  servlet:
    context-path: /management/v1
  error:
    include-binding-errors: always
    include-message: always
management:
  security:
    enabled: false
management.endpoints.web.exposure.include: "health,info"
management.endpoint.health.show-details: always
management.endpoint.health.probes.enabled: true

spring:
  main:
    allow-bean-definition-overriding: true
  r2dbc:
    url: "r2dbc:postgresql://localhost:5432/happy_test?stringtype=unspecified"
    username: postgres
    password: iloveyou
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      #      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
    consumer:
      #      bootstrap-servers: localhost:9092
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
  #      group-id: my-reactive-group

kafka:
  topic:
    sync-person: dev.management.person
  group:
    sync-person: dev.management

person-manager:
  http:
    baseUrl: http://localhost:3031



